server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm-stats
    username: stats
    password: stats
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info