# ДЛЯ ЛОКАЛЬНОГО ЗАПУСКА ТЕСТОВ

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:6542/ewm_main
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.query.escapeCharacter: "\\"
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

#stats:
#  url: ""   # локально статистику отключаем

stats:
  url: http://localhost:9090

app:
  name: ewm-main-service